winzou_state_machine:
    app_supplier:
        class: "%app.model.supplier.class%"
        property_path: status
        graph: app_supplier
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            trusted: ~
        transitions:
            trust:
                from: [new]
                to: trusted
